# force to go for VM container : it has more RAM, necessary for Xtend compilation and update site compression steps
# sudo : required

# workaround issue : https://github.com/travis-ci/travis-ci/issues/7685
sudo: required
dist: precise

install: true

language: java

before_script:
 - echo $JAVA_OPTS
 - export JAVA_OPTS='-Xms1g -Xmx3g'
 - echo "MAVEN_OPTS='-Xmx3g'" > ~/.mavenrc

script : cd fr.lip6.move.gal.parent && mvn -e -t 4 generate-sources install && cd - 

jdk: oraclejdk8

env:
  global:
    - MAVEN_OPTS="-Xmx3g"

cache:
  directories:
    - '$HOME/.m2/repository'

  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: fr.lip6.move.gal.updatesite/target/repository
  on:
    branch: master
