install: true

language: java

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"

script : cd fr.lip6.move.gal.parent && mvn -e -t 2 clean generate-sources install && cd - 

jdk: oraclejdk8

env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx4g"

cache:
  directories:
    - '$HOME/.m2/repository'

  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: fr.lip6.move.gal.updatesite/target/repository
  on:
    branch: master
